name: Run Tests
on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        node_version: [14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: |
          npm install
      - name: Instrospection of node version impact
        run: |
          cat package-lock.json
          find node_modules | xargs md5sum
      - name: Test
        run: |
          npm run test:once
